splunk/addonfactory-solutions-library-python

examples/test_metadata.py
examples/test_server_info.py
examples/test_user_access.py

- In test_metadeta.py in python 3 it was getting converted to byte format and unicode in python2 so used six package which matches unicode in python2 and string in python3.
- In test_user_access used set to match list.
- In test_serverinfo the exception message printed was python2 specific to updated that to make it python2 and python3 compatible.

Pr for failure fix

---

solnlib/modular_input/checkpointer.py

Exception was passed to traceback.format_exc which is incorrect and it caused `TypeError: '>=' not supported between instances of 'HTTPError' and 'int'` error.

fix: incorrect usage of traceback.format_exc function

---

poetry.lock
pyproject.toml

This is the same PR as https://github.com/splunk/addonfactory-solutions-library-python/pull/95 but it has a fix prefix, so we can release a new version with new version of `splunk-sdk`.

fix: splunk-sdk update to 1.6.17

---

solnlib/utils.py
tests/unit/test_utils.py

Removes escape_json_control_chars and unescape_json_control_chars as they are not used across add-ons and should not be a part of solnlib.

fix: remove json related functions

---

solnlib/server_info.py
tests/integration/test_server_info.py
tests/unit/test_server_info.py

This commit introduces 2 new methods for ServerInfo class, 2 methods that are missing from splunktalib's implementation of ServerInfo.
After this commit is merged, splunktalib's implementation can be deprecated, because solnlib's implementation supports everything and even more.

feat: add ServerInfo's from_server_uri and to_dict

---

tests/unit/test_file_monitor.py

This test was passing locally, but it is actually flaky and not passing every time in CI.

test: remove flaky test

---

solnlib/utils.py
tests/unit/test_utils.py

This PR provides a new function that was in `splunktalib`. Reference issue: https://github.com/splunk/addonfactory-ta-library-python/issues/38

feat: add remove_http_proxy_env_vars function

---

.github/workflows/build-test-release.yml

From `poetry` [README](https://github.com/python-poetry/poetry#installation):
Warning: The previous get-poetry.py installer is now deprecated, if you are currently using it you should migrate to the new, supported, install-poetry.py installer.

ci: update poetry installation command

---

solnlib/splunkenv.py
tests/unit/test_splunkenv.py

It seems that you can add ipv6 string for web.settings.mgmtHostPort stanza.
Docs: https://docs.splunk.com/Documentation/Splunk/9.0.0/Admin/ConfigureSplunkforIPv6

feat: add support for ipv6 in web.settings.mgmtHostPort stanza

---

.github/workflows/build-test-release.yml
solnlib/modular_input/event.py
solnlib/modular_input/event_writer.py
tests/integration/_search.py
tests/integration/test_hec_event_writer.py
tests/unit/test_modular_input_event_writer.py

To reproduce:
```python
data = {"field_a": "Üü_Öö_Ää_some_text", "field_b": "some_text_Üü_Öö_Ää"}
event = event_writer.create_event(data, time=time.time(), source="solnlib_demo", sourcetype="solnlib_demo")
event_writer.write_events([event])
```
When indexing data with special characters, these are implicitly UTF-8 encoded.
Here how the raw data looks like in Splunk:
Searching for field_a="Üü_Öö_Ää_some_text" is not working. The only way is to use star (*):
`field_a="*_some_text"`
which is very inefficient if the first character is an umlaut.
The other workaround would be to search for
`field_a="\u00dc\u00fc_\u00d6\u00f6_\u00c4\u00e4_some_text"`
which is not practicable.
We are using the "Splunk Add-on for Microsoft Cloud Services" app, which is using solnlib …

fix: handle JSON character encoding for hec (Umlauts)

---

.github/workflows/build-test-release.yml
solnlib/log.py
solnlib/modular_input/modular_input.py
tests/unit/test_log.py

Current implementation has a function for start and end of modular input and a function to report how many events were ingested into Splunk using some particular sourcetype.

feat: introduce initial functions for some specific logging events

---

solnlib/log.py
tests/unit/test_log.py

If we just use sourcetype, it is being shadowed by Splunk's own sourcetype field during the dashboard creation and does not properly reflect the sourcetype where the data is being ingested.

fix: sourcetype renamed to sourcetype_ingested

---

.github/workflows/docs.yaml
poetry.lock
pyproject.toml

Release a fix for https://github.com/splunk/addonfactory-solutions-library-python/security/dependabot/4.

fix: require requests 2.31.0 and urllib3 < 2

---

renovate.json

Splunk add-ons only support urllib3 < 2 as of now, so configuring renovate not to send updates for urllib3 >= 2.

chore: pin urllib3 to <2 for renovate

---

poetry.lock
pyproject.toml

This PR introduces less constraints for some of the dependencies used in this library so consumers can benefit from widen ranges.

chore: relax dependency versions

---

.github/workflows/build-test-release.yml

Some of tests are failing using Splunk 9.0.x. It seems that KVStore needs a bit more time to initialize after the restart. Adding corresponding check.

ci: check for KVStore status before running tests

---

.github/workflows/build-test-release.yml

fix `"an artifact with this name already exists"` error

chore: change artifact name

---

solnlib/log.py
tests/unit/test_log.py

this feature adds exception logging functionality

feat: add exception logging function, add tests

---

.releaserc

Tested in regex101.com.
It captured `mkdocstrings = {version=">=0", extras=["python"]}` as well which we don't need.
Fixes https://github.com/splunk/addonfactory-solutions-library-python/actions/runs/7713020796/job/21022116056#step:6:502

ci: fix regex to capture only necessary version update

---

solnlib/log.py
tests/unit/test_log.py

Extended the `events_ingested` function to log more information such as index, host, account and input.

feat: extend events_ingested to accommodate UCC health check page

---

solnlib/conf_manager.py
tests/unit/test_conf_manager.py

Allow developers to pass their logging stanza name while getting the log level via `conf_manager.py`.

fix(log_level): update fetching loglevel with stanza

---

solnlib/log.py
tests/unit/test_log.py

**Issue number:[ADDON-68670](https://splunk.atlassian.net/browse/ADDON-68670)**
Extending log module with new error logging functions. Breaking change for `log_exception` function.
* added new functions for error logging.
* added `exc_l` parameter to logging message to categorize errors.
* added `exc_l` parameter to `log_exception` function as a mandatory argument to log errors with custom category.
* user can categorize errors in the add-on using new functions. For now 5 basic categories are prepered: Authentication, Permission, Connection, Configuration, Server.
* user can add custom error category using `log_exception` function by adding another args `exc_label`
* all user's current use of the `log_exception` function must be extended with a `exc_label` argument to categorize error.
If …

BREAKING CHANGE: add logging function for basic error types

---

solnlib/log.py
tests/unit/test_log.py

BREAKING CHANGE: add logging function for basic error types

feat: merge develop into main

---

docs/bulletin_rest_client.md
mkdocs.yml
solnlib/__init__.py
solnlib/bulletin_rest_client.py
tests/integration/test_bulletin_rest_client.py
tests/unit/test_bulletin_rest_client.py

**Issue number:[ADDON-70528](https://splunk.atlassian.net/browse/ADDON-70528)**
Create REST client to manage bulletin messages in splunk.
* add bulletin_rest_client module with basic methods: CREATE, GET, GET ALL, DELETE 
The user can better manage events in add-on by creating specific messages in the Splunk bulletin. Every message has 3 severity levels: info, warn, error. The user can also delete or read those messages at code lvl with the use of REST client. 
If your change doesn't seem to apply, please leave them unchecked.

feat: add bulletin_rest_client module to manage global Splunk messages

---

.github/workflows/build-test-release.yml
.gitignore
solnlib/server_info.py
solnlib/splunk_rest_client.py
tests/integration/conftest.py
tests/unit/conftest.py
tests/unit/test_server_info.py

ADDON-70857
Added fetching of the client certificates for mTLS communication for `ServerInfo` class.

feat(mtls): implement of mutual TLS communication for fetching server info.

---

.releaserc

chore: remove skip ci from releaserc

---

solnlib/server_info.py
tests/unit/conftest.py
tests/unit/test_server_info.py

Handle imports when Splunk isn't present.

fix(server_info): handle splunk not present imports

---

solnlib/modular_input/event_writer.py
tests/unit/test_modular_input_event_writer.py

When create_from_token() is invoked, it triggers the HECEventWriter constructor with scheme, host, and port set to None. This leads to a get_splunkd_access_info() call, which throws an exception if the HEC URI doesn’t reference the local machine. As this call is unnecessary in such cases, its invocation has been relocated within the if-statement

fix: standalone HECEventwriter

---

solnlib/log.py
tests/unit/test_log.py

This PR adds a new event field to logs (log_level).
Example log before this change:
```
2024-07-15 10:01:22,969 ERROR pid=49789 tid=MainThread file=helper_one.py:stream_events:19 | Test log
```
Example log after this change:
```
2024-07-15 10:01:22,969 log_level=ERROR pid=49789 tid=MainThread file=helper_one.py:stream_events:19 | Test log
```

feat: add log_level attribute

---

solnlib/log.py
tests/integration/test_bulletin_rest_client.py
tests/unit/test_log.py

**Issue number: [ADDON-72793](https://splunk.atlassian.net/browse/ADDON-72793)**
Added support for custom source in license usage
function `events_ingested` has new optional parameter `license_usage_source`. If provided this value will be save as `modular_input_name`.

fix: add support of custom source in license usage

---

.github/workflows/build-test-release.yml

Updated the build-test-release workflow to use [sast-scan](https://github.com/splunk/sast-scanning) owned by product security team instead of using custom implementation.
Ref: https://splunk.atlassian.net/browse/ADDON-72309

refactor: use reusable workflow for semgrep

---

solnlib/splunk_rest_client.py
tests/unit/test_splunk_rest_client.py

**Issue number:[ADDON-75327](https://splunk.atlassian.net/browse/ADDON-75327)**
Added functionality to retries requests.
Added "max_retries" to the "HTTPAdapter" and set it to 5.
No impact / potential reliability improvement
If your change doesn't seem to apply, please leave them unchecked.

feat: add retry functionality to the splunk_rest_client

---

.github/workflows/build-test-release.yml
.github/workflows/docs.yaml
.pre-commit-config.yaml

This PR sets ubuntu version to 22.04 for scripts run with python 3.7.
Reference: [ADDON-75861](https://splunk.atlassian.net/browse/ADDON-75861)
Python version for pre-commit can not be updated to latest version due to open issue with the docformatter hook.
Reference: https://github.com/PyCQA/docformatter/issues/289, https://github.com/PyCQA/docformatter/issues/293

ci: fix ubuntu version to 22.04

---

poetry.lock
pyproject.toml

Similar to https://github.com/splunk/addonfactory-ucc-generator/pull/1452.
So we could properly see the classifiers on PyPI (see screenshot below).

chore(pyproject): explicitly specify supported Python versions

---

.github/workflows/build-test-release.yml
.github/workflows/docs.yaml
poetry.lock
pyproject.toml

Syncing commits from main branch to develop branch.

chore: sync commits across branches

---

docs/release_6_0_0.md
mkdocs.yml
poetry.lock
pyproject.toml

**Issue number:[ADDON-73536](https://splunk.atlassian.net/browse/ADDON-73536)**
**What kind of change does this PR introduce?**
The requests library has been removed from solnlib, so solnlib now depends on the requests library from the running environment.
removed requests from pyproject.toml
Solnlib will no longer install requests library. if requests are installed in `<Add-on>/lib` e.g. as a dependency of another library, that version will be taken first. If requests is missing from the add-on’s lib directory, then requests provided from splunk will be used. In case the splunk requests version is not sufficient for the user, user can deliver version he needs by simply adding it to the requirements.txt or pyproject.toml file in the add-on.
If an item doesn't apply to your changes, leave …

BREAKING CHANGE: removed requests from solnlib's dependencies

---

poetry.lock
pyproject.toml

Jira: https://splunk.atlassian.net/browse/ADDON-77054
This PR makes sure that `solnlib` will require at least `2.0.2` version of `splunk-sdk`.

fix: require splunk-sdk at least 2.0.2

---

solnlib/concurrent/concurrent_executor.py
solnlib/concurrent/process_pool.py
solnlib/concurrent/thread_pool.py
solnlib/modular_input/modinput.py
solnlib/rest.py
solnlib/schedule/job.py
solnlib/schedule/scheduler.py
solnlib/utils.py

[ADDON-73693](https://splunk.atlassian.net/browse/ADDON-73693)
Migrated all the methods of `splunktalib` which were used in `splunktaucclib` to `solnlib`

feat: moved methods from splunktalib

---

.github/workflows/build-test-release.yml

Splunk 9.4 introduced a change in package name (see [Slack thread](https://splunk.slack.com/archives/C9YN6R66A/p1736523466831319)), from:
`splunk-${SPLUNK_VERSION}-${SPLUNK_BUILD}-Linux-x86_64.tgz`
to
`splunk-${SPLUNK_VERSION}-${SPLUNK_BUILD}-linux-amd64.tgz`

ci: fix download url for Splunk >= 9.4

---

solnlib/splunk_rest_client.py
tests/integration/test_splunk_rest_client.py

**Issue number:** [ADDON-76041](https://splunk.atlassian.net/browse/ADDON-76041)
**What kind of change does this PR introduce?**
Changed "User-Agent" header parameter from `Curl` to `solnlib/<version> rest-client <os platform>`
The user will see more detailed "User-Agent" information in the logs regarding requests made using the rest client.
If an item doesn't apply to your changes, leave it unchecked.

feat: improve information in the user-agent param

---

solnlib/splunkenv.py

Method get_conf_stanzas internally calls
`$SPLUNK_HOME/bin/splunk cmd btool server list`
This command leads to accumulated output. It reads server.conf files from all apps.
Such behaviour may lead to invalid results, if an app has different (not supported) format in the conf file.
I suggest to change login and read configs only from the system app:
`$SPLUNK_HOME/bin/splunk cmd btool server list --app=system`

fix: Splunk metadata parsing logic: config stanzas must be loaded from the system app

---

solnlib/server_info.py

SPL-264208 MSB-3468 Update python library to support mTLS when web private key is encrypted

feat: support mTLS when web private key is encrypted
